// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: proto/auth.proto

/* eslint-disable */

export const protobufPackage = "example_db";

/** Message for the User entity */
export interface User {
  userId: number;
  username: string;
  email: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

/** Message for the Role entity */
export interface Role {
  roleId: number;
  roleName: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

/** Message for the UserRole join table */
export interface UserRole {
  userId: number;
  roleId: number;
  assignedAt: Date | undefined;
}
